apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raffle
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: cuvva-nonprod
  source:
    path: charts/basil/raffle
    #    helm:
    repoURL: https://github.com/tgmendes/argo-config-helm
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true