apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-argo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: hello-argo
    #    helm:
    repoURL: https://github.com/tgmendes/argo-config
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true